export const metadata = {
  title: "Shanta",
  description: "Generated by Shanta",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <div>FOOTER</div>
      </body>
    </html>
  );
}
